# Hola mundo
GET http://localhost:3000/

###

###

# Traer todos los actores
GET http://localhost:3000/actors

###

# Crear un actor
POST http://localhost:3000/actors
Content-Type: application/json

{
  "nombre": "Lionel",
  "apellido": "Messi"
}

###

# Traer todos los contenidos
GET http://localhost:3000/contenido

###

# Crear contenido
POST http://localhost:3000/contenido
Content-Type: application/json

[
  {
    
    "poster": "./posters/36.jpg",
    "titulo": "la vida de un tuerto",
    "categoria": "Película",
    "gen": "Suceso Real",
    "genero": "Drama, Historia, Tecnología",
    "busqueda": "JOBS: La Vida De Steve Jobs, Drama, Historia, Biopic, Suceso Real, Ahston Kutcher, Dermot Mulroney, Josh Gad, Lukas Haas, Matthew Modine, J.K. Simmons, Lesley Ann Warren, Apple, Cupertino",
    "resumen": "Sólo hace falta una persona para empezar una revolución. Jobs es la extraordinaria historia de Steve Jobs, el original innovador y emprendedor que no dejó que nada se interpusiera en su camino hacia la grandeza. La película cuenta la épica y turbulenta historia de Jobs mientras abría un camino que cambió la tecnología - y el mundo - para siempre. Su vida es repasada desde que era adolescente, intentando estudiar en la universidad, hasta el año 2001, cuando el iPod fue presentado al mundo y comenzó a 'allanar' el camino para lo que años después, sería el iPhone.",
    "temporadas": "N/A",
    "duracion": "104 minutos",
    "reparto": "Ahston Kutcher",
    "trailer": "https://www.youtube.com/embed/FrvkCS0ZGPU"
  },
]


###
# actulizar por id
PUT http://localhost:3000/actualizar/17
Content-Type: application/json

{
  "id": 11,
  "poster": "./posters/4.jpg",
  "titulo": "la nona loca",
  "categoria": "Serie",
  "genero": "Sci-Fi, Fantasía, Acción",
  "gen": "Ciencia Ficción",
  "busqueda": "",
  "resumen": "",
  "temporadas": 1,
  "reparto": "",
  "trailer": "https://www.youtube.com/embed/aOC8E8z_ifw"
}

###
# filtrar por genero, categoria o titulo
GET http://localhost:3000/contenido/buscar?categoria=Serie

###

# Traer por id
GET http://localhost:3000/contenido/15

###

# eliminar por id
DELETE  http://localhost:3000/eliminar/6


